      ******************************************************************
      * Created: Fri, 16 Feb 2024 09:51:13 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: A2200ADDCUST
      * Workbook id: e587dcf0-73f0-4a0c-b8a2-2466f2b75e4f
      * Project: $clientCOBOL_49eb5263-c696-4ff9-8e35-5a9537fc7091
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. A2200ADD.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
      ******************************************************************
       COPY CUSTTRAN.
      * PATH : .../Cobol Include/CUSTTRAN.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 CUSTINPT-FILE.
      *    05 CUSTIN-CUSTM-DOB                  PIC X(10).
      *    05 CUSTIN-PRI-KEY.
      *       10 CUSTIN-REQ-TYPE                PIC X(02).
      *       10 CUSTIN-CUSTM-NO                PIC X(10).
      *    05 CUSTIN-CUSTM-NAME-FRSTNM          PIC X(15).
      *    05 CUSTIN-CUSTM-NAME-MDLNM           PIC X(8).
      *    05 CUSTIN-CUSTM-NAME-LASTNM          PIC X(15).
      *    05 CUSTIN-CUSTM-ADDR                 PIC X(35).
      ******************************************************************
      * PATH : .../zOS Cobol/PGBTXN
       01 WS-MISC-VAR.
         05  WS-SUBPGM                   PIC X(06) VALUE 'SUBPGM'.
      ******************************************************************

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBTXN
      * PROGRAM PATH : .../zOS Cobol/PGBTXN
      * STMT START LINE NUMBER : 145
      * STMT END LINE NUMBER : 147
       A2200-ADD-CUST-PARA.

           CALL WS-SUBPGM USING CUSTINPT-FILE.
      ******************************************************************
           EXIT PROGRAM.
