      ******************************************************************
      * Created: Mon, 5 Feb 2024 09:21:34 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: WB2-Feb5
      * Workbook id: ceb07bfb-9f05-48ed-8931-7617133475a2
      * Project: $clientCOBOL_fa79be2a-c77c-4d3f-a56e-fdec6fe02b1f
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. FEB05.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
      ******************************************************************
       COPY CUSTMSTR.
      * PATH : .../Cobol Include/CUSTMSTR.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01  DCLACN-CUSTM-TABLE.
      *    10 ACN-CUSTM-NAME-MDLNM PIC X(8).
      *    10 ACN-CUSTM-NAME-LASTNM PIC X(15).
      *    10 ACN-CUSTM-ADDR       PIC X(35).
      *    10 ACN-CUSTM-DOB        PIC X(10).
      *    10 ACN-CUSTM-NO          PIC S9(9) USAGE COMP.
      *    10 ACN-CUSTM-NAME-FRSTNM PIC X(15).
      ******************************************************************
       COPY CUSTTRAN.
      * PATH : .../Cobol Include/CUSTTRAN.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 CUSTINPT-FILE.
      *    05 CUSTIN-PRI-KEY.
      *       10 CUSTIN-CUSTM-NO                PIC X(10).
      *    05 CUSTIN-CUSTM-NAME-FRSTNM          PIC X(15).
      *    05 CUSTIN-CUSTM-NAME-MDLNM           PIC X(8).
      *    05 CUSTIN-CUSTM-NAME-LASTNM          PIC X(15).
      *    05 CUSTIN-CUSTM-ADDR                 PIC X(35).
      *    05 CUSTIN-CUSTM-DOB                  PIC X(10).
      ******************************************************************
        COPY SQLCA.
      * PATH : .../Cobol Include/SQLCA.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      * 01 SQLCA.
      *    05 SQLCODE     PIC S9(9) COMP-5.
      ******************************************************************

      * SQLCA DB2 communications area
           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 190
      * STMT END LINE NUMBER : 213
       A2300-MOD-CUST-PARA.
           MOVE CUSTIN-CUSTM-NO           TO ACN-CUSTM-NO.
           MOVE CUSTIN-CUSTM-NAME-FRSTNM  TO ACN-CUSTM-NAME-FRSTNM.
           MOVE CUSTIN-CUSTM-NAME-MDLNM   TO ACN-CUSTM-NAME-MDLNM.
           MOVE CUSTIN-CUSTM-NAME-LASTNM  TO ACN-CUSTM-NAME-LASTNM.
           MOVE CUSTIN-CUSTM-ADDR         TO ACN-CUSTM-ADDR.
           MOVE CUSTIN-CUSTM-DOB          TO ACN-CUSTM-DOB.

           EXEC SQL
                UPDATE CUSTM_TABLE   SET
                  CUSTM_NAME_FRSTNM = :ACN-CUSTM-NAME-FRSTNM,
                  CUSTM_NAME_MDLNM = :ACN-CUSTM-NAME-MDLNM,
                  CUSTM_NAME_LASTNM = :ACN-CUSTM-NAME-LASTNM,
                  CUSTM_ADDR = :ACN-CUSTM-ADDR,
                  CUSTM_DOB  = :ACN-CUSTM-DOB
                WHERE CUSTM_NO = :ACN-CUSTM-NO
              END-EXEC.

           EVALUATE TRUE
            WHEN SQLCODE = 0
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                 CONTINUE
            WHEN OTHER
                 DISPLAY 'CUST TABLE UPDATE SQLCODE -',SQLCODE
           END-EVALUATE.
      ******************************************************************
           EXIT PROGRAM.
