      ******************************************************************
      * Created: Tue, 13 Feb 2024 09:42:21 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: WBFEB13
      * Workbook id: 42831ad6-954d-4f81-9ee4-dcf8adf8cede
      * Project: $clientCOBOL_fa79be2a-c77c-4d3f-a56e-fdec6fe02b1f
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. LOANMSTR.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
      ******************************************************************
      * PATH : .../zOS Cobol/PGBPRTXN.cbl
       01 WS-MISC-VAR.
         05  WS-TEMP-LOAN-NO                      PIC X(10).
         05  WS-LOAN-NO                           PIC S9(9) USAGE COMP.
      ******************************************************************
       COPY LOANTRAN.
      * PATH : .../Cobol Include/LOANTRAN.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 LOANINPT-FILE.
      *    05 LOANIN-LLOANM-CUST-NO       PIC X(10).
      *    05 LOANIN-LLOANM-CAT           PIC X(2).
      ******************************************************************
        COPY SQLCA.
      * PATH : .../Cobol Include/SQLCA.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      * 01 SQLCA.
      *    05 SQLCODE     PIC S9(9) COMP-5.
      ******************************************************************
       COPY LOANMSTR.
      * PATH : .../Cobol Include/LOANMSTR.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01  DCLLOANMSTR.
      *    10 LLOANM-CAT           PIC X(2).
      *    10 LLOANM-CUST-NO       PIC X(10).
      ******************************************************************

      * SQLCA DB2 communications area
           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 257
      * STMT END LINE NUMBER : 278
       A3210-SEARCH-LOANMSTR.
              INITIALIZE WS-LOAN-NO
                         WS-TEMP-LOAN-NO.

              MOVE LOANIN-LLOANM-CAT      TO  LLOANM-CAT.
              MOVE LOANIN-LLOANM-CUST-NO  TO  LLOANM-CUST-NO.

              EXEC SQL
                   SELECT LOANM_NO INTO :WS-LOAN-NO
                   FROM LOANMSTR
                   WHERE LOANM_CAT = :LLOANM-CAT AND
                         LOANM_CUST_NO = :LLOANM-CUST-NO
              END-EXEC.

              EVALUATE TRUE
              WHEN SQLCODE = 0
                 MOVE WS-LOAN-NO               TO WS-TEMP-LOAN-NO
              WHEN SQLCODE = 100
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                  CONTINUE
              WHEN OTHER
                  DISPLAY 'LOAN TABLE SELECT SQLCODE -',SQLCODE
              END-EVALUATE.
      ******************************************************************
           EXIT PROGRAM.
