      ******************************************************************
      * Created: Wed, 7 Feb 2024 14:01:54 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: COMPLETE
      * Workbook id: ebb4dadb-4d66-4edb-9701-26783ed5c70e
      * Project: $clientCOBOL_fa79be2a-c77c-4d3f-a56e-fdec6fe02b1f
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. NEWALL.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
      ******************************************************************
           SELECT INPUT-FILE     ASSIGN I1DQ0001.
      ******************************************************************
           SELECT OUTPUT-FILE    ASSIGN O1DQ0001.
      ******************************************************************

       DATA DIVISION.
       FILE SECTION.
      ******************************************************************
       FD  INPUT-FILE
           LABEL RECORD STANDARD
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.

      ******************************************************************
      * PATH : .../zOS Cobol/RV3C0100.cbl
       01  RE-INPUT                        PIC X(750).
      ******************************************************************
       FD  OUTPUT-FILE
           LABEL RECORD STANDARD
           BLOCK CONTAINS 0 RECORDS
           RECORDING MODE IS F.

      ******************************************************************
      * PATH : .../zOS Cobol/RV3C0100.cbl
       01  RE-OUTPUT                       PIC X(750).
      ******************************************************************

       WORKING-STORAGE SECTION.
      ******************************************************************
      * PATH : .../zOS Cobol/RV3C0100.cbl
       01  VA-SW.
           05  SW-INP-END                   PIC X(1).
               88  INP-NO-END                       VALUE 'N'.
               88  INP-YES-END                      VALUE 'S'.
       01  VA-QBEC999-01.
      ******************************************************************
       COPY QBEC999.
      * PATH : .../Cobol Include/QBEC999.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *02 QBEC999.
      *   05 QBEC999-DATA-PARAM.
      *      10 QBEC999-COD-ENTITY                   PIC X(04).
      *      10 QBEC999-ENTITY-DATA.
      *         15 QBEC999-FREE                      PIC X(14).
      *         15 QBEC999-LNG-DATA                  PIC X(01).
      *         15 QBEC999-COD-SHORT                 PIC X(02).
      *         15 QBEC999-COD-NB                    PIC X(04).
      *         15 QBEC999-COD-NATCC                 PIC X(03).
      *         15 QBEC999-COD-NATCCSHORT            PIC X(01).
      *         15 QBEC999-COD-OCCCTRY               PIC X(03).
      *         15 QBEC999-COD-OFCCSHORT             PIC X(01).
      *         15 QBEC999-COD-RCC                   PIC X(03).
      *         15 QBEC999-COD-RFCCSHORT             PIC X(01).
      *         15 QBEC999-COD-NRESFCC               PIC X(03).
      *         15 QBEC999-COD-NATCTRY               PIC X(03).
      *         15 QBEC999-FLG-EURCTRY               PIC X(01).
      *            88 QBEC999-88-FLGYESEURCTRY       VALUE 'S'.
      *            88 QBEC999-88-FLGNONEURCTRY       VALUE 'N'.
      *         15 QBEC999-FLG-EXCHANGE              PIC X(01).
      *            88 QBEC999-88-FLGDIRCHG           VALUE 'D'.
      *            88 QBEC999-88-FLGINDIRCHG         VALUE 'I'.
      *         15 QBEC999-LNG-OFDATA                PIC X(01).
      *         15 QBEC999-FLG-OFCACC                PIC X(01).
      *         15 QBEC999-FCCCOEXC                  PIC X(01).
      *         15 QBEC999-FLG-LNG1                  PIC X(01).
      *         15 QBEC999-FLG-LNG2                  PIC X(01).
      ******************************************************************
      * PATH : .../zOS Cobol/RV3C0100.cbl
       01  VA-ALCONS.
           05  CA-LOAN                     PIC X(2)    VALUE '96'.
           05  CA-DEPOSIT1                 PIC X(2)    VALUE '01'.
           05  CA-DEPOSIT2                 PIC X(2)    VALUE '02'.
           05  CA-DEPOSIT3                 PIC X(2)    VALUE '07'.
           05  CA-QB8C9900                 PIC X(8)  VALUE 'QB8C9900'.
           05  CA-PROGRAM                  PIC X(8)  VALUE 'RV3C0100'.
           05  CA-QR4CDB0                  PIC X(7)  VALUE 'QR4CDB0'.
           05  CA-A                        PIC X     VALUE 'A'.
       01  VA-QBEC9900-01.
      ******************************************************************
       COPY QBEC9900.
      * PATH : .../Cobol Include/QBEC9900.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *02 QBEC9900.
      *   05 QBEC9900-OUTPUTFLD.
      *      10 QBEC9900-DATA-PARAM.
      *         15 QBEC9900-FLG-EXCHANGE             PIC X(01).
      *            88 QBEC9900-88-FLGDIRCHG          VALUE 'D'.
      *            88 QBEC9900-88-FLGINDIRCHG        VALUE 'I'.
      *         15 QBEC9900-LNG-OFDATA               PIC X(01).
      *         15 QBEC9900-FLG-OFCACC               PIC X(01).
      *         15 QBEC9900-FCCCOEXC                 PIC X(01).
      *         15 QBEC9900-FLG-LNG1                 PIC X(01).
      *         15 QBEC9900-FLG-LNG2                 PIC X(01).
      *         15 QBEC9900-FREE                     PIC X(14).
      *         15 QBEC9900-COD-ENTITY               PIC X(04).
      *         15 QBEC9900-LNG-DATA                 PIC X(01).
      *         15 QBEC9900-COD-SHORT                PIC X(02).
      *         15 QBEC9900-COD-NB                   PIC X(04).
      *         15 QBEC9900-COD-NATCC                PIC X(03).
      *         15 QBEC9900-COD-NATCCSHORT           PIC X(01).
      *         15 QBEC9900-COD-OCCCTRY              PIC X(03).
      *         15 QBEC9900-COD-OFCCSHORT            PIC X(01).
      *         15 QBEC9900-COD-RCC                  PIC X(03).
      *         15 QBEC9900-COD-RFCCSHORT            PIC X(01).
      *         15 QBEC9900-COD-NRESFCC              PIC X(03).
      *         15 QBEC9900-COD-NATCTRY              PIC X(03).
      *         15 QBEC9900-FLG-EURCTRY              PIC X(01).
      *            88 QBEC9900-88-FLGYESEURCTRY      VALUE 'S'.
      *            88 QBEC9900-88-FLGNONEURCTRY      VALUE 'N'.
      *      10 QBEC9900-FLD-DES-LNGS                OCCURS 3 TIMES.
      *         15 QBEC9900-LNG-DATA-0               PIC X(01).
      *         15 QBEC9900-DATA-DESCRIP-0.
      *            20 QBEC9900-DES-NRESFCC-0         PIC X(20).
      *            20 QBEC9900-DES-NATCTRY-0         PIC X(40).
      *            20 QBEC9900-SDE-ENTITY-0          PIC X(10).
      *            20 QBEC9900-DES-ENTITY-0          PIC X(40).
      *            20 QBEC9900-DES-NB-0              PIC X(40).
      *            20 QBEC9900-DES-NATCC-0           PIC X(20).
      *            20 QBEC9900-SDE-FCC-0             PIC X(03).
      *            20 QBEC9900-DES-OCC-0             PIC X(20).
      *            20 QBEC9900-SDES-ORIFCC-0         PIC X(03).
      *            20 QBEC9900-DES-REFFCC-0          PIC X(20).
      *      10 QBEC9900-DATA-DESCRIP.
      *         15 QBEC9900-DES-OCC                  PIC X(20).
      *         15 QBEC9900-SDES-ORIFCC              PIC X(03).
      *         15 QBEC9900-DES-REFFCC               PIC X(20).
      *         15 QBEC9900-DES-NRESFCC              PIC X(20).
      *         15 QBEC9900-DES-NATCTRY              PIC X(40).
      *         15 QBEC9900-SDE-ENTITY               PIC X(10).
      *         15 QBEC9900-DES-ENTITY               PIC X(40).
      *         15 QBEC9900-DES-NB                   PIC X(40).
      *         15 QBEC9900-DES-NATCC                PIC X(20).
      *         15 QBEC9900-SDE-FCC                  PIC X(03).
      *   05 QBEC9900-RETURN-DATA.
      *      10 QBEC9900-COD-RETURN                  PIC X(02).
      *         88 QBEC9900-88-COD-RETURN-OK         VALUE '00'.
      *         88 QBEC9900-88-COD-RETURN-NOTFND     VALUE '10'.
      *         88 QBEC9900-88-COD-RETURN-OTHERS     VALUE '99'.
      *      10 QBEC9900-FILE-STATUS                 PIC X(02).
      ******************************************************************
       COPY QRECDB2.
      * PATH : .../Cobol Include/QRECDB2.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 QRECDB2.
      *   05 DB2-CODERR                    PIC X(7).
      *   05 DB2-SQLCA                     PIC X(136).
      *   05 DB2-DES-PGM                   PIC X(8).
      *   05 DB2-OBJECT                    PIC X(8).
      *   05 DB2-STATEMENT                 PIC X(8).
      *   05 DB2-ABEND                     PIC X(1).
      *   05 DB2-ABEND-DB2                 PIC X(1).
      *   05 DB2-REFERENCE1                PIC X(120).
      *   05 DB2-QR4CDB0                   PIC X(8) VALUE 'QR4CDB0'.
      *   05 DB2-SW-SQLCA                  PIC X(1).
      *      88 DB2-SW-SQLCA-ALL                    VALUE '0', ' '.
      *      88 DB2-SW-SQLCA-PART                   VALUE '1'.
      *   05 DB2-SQLCODE                   PIC S9(9) COMP.
      *   05 DB2-SQLERRM                   PIC X(70).
      *   05 DB2-RETURN-CODE               PIC S9(04) COMP.
      *   05 FILLER                        PIC X(35).
      ******************************************************************
       COPY RVFC007.
      * PATH : .../Cobol Include/RVFC007.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01  RVFC007.
      *05  F007-DTA-RIECCIM.
      *    10  F007-AMT-PENDCAP            PIC S9(13)V99 COMP-3.
      *    10  F007-AMT-PENDCAP-A1   REDEFINES F007-AMT-PENDCAP
      *                                    PIC X(8).
      *    10  F007-AMT-LEGALCO            PIC S9(13)V99 COMP-3.
      *    10  F007-AMT-LEGALCO-A1   REDEFINES F007-AMT-LEGALCO
      *                                    PIC X(8).
      *    10  FILLER                      PIC X(02).
      *    10  F007-DAT-RCPT               PIC X(10).
      *    10  F007-DAT-PROV               PIC X(10).
      *    10  F007-PER-CAP                PIC X(4).
      *    10  F007-PER-IRT                PIC X(4).
      *    10  F007-AMT-CAP                PIC S9(13)V9(2) COMP-3.
      *    10  F007-AMT-ITR                PIC S9(13)V9(2) COMP-3.
      *    10  F007-AMT-COM                PIC S9(13)V9(2) COMP-3.
      *    10  F007-AMT-EXPN               PIC S9(13)V9(2) COMP-3.
      *    10  F007-AMT-ARR                PIC S9(13)V9(2) COMP-3.
      *    10  F007-PER-ARR                PIC S9(2)V9(3) COMP-3.
      *    10  F007-FLG-AVA1-A1            PIC X(1).
      *05  F007-DTA-RVECASN.
      *    10  F007-COD-STOBJDEBT          PIC X(02).
      *    10  F007-COD-STSUBJDEBT         PIC X(02).
      *    10  FILLER                      PIC X(06).
      *05  F007-DECLIN-RSN                 PIC X(225).
      *05  F007-DECLIN-BRN                 PIC X(6).
      *    05  F007-CRRRISK.
      *        10  F007-AMT-PROV           PIC S9(15)V9(2) COMP-3.
      *        10  F007-FLG-INTST          PIC X(3).
      *        10  F007-KEY-CBRISK         PIC X.
      *        10  F007-FCC                PIC X(3).
      *        10  F007-KEY-CBTERM         PIC X.
      *        10  F007-KEY-CBCOLT         PIC X.
      *        10  F007-KEY-CBST           PIC X.
      *        10  F007-NCBA               PIC X(5).
      *        10  F007-COD-SRGN           PIC S9(3) COMP-3.
      *        10  F007-COD-CBSEC          PIC S9(8) COMP-3.
      *        10  F007-AMT-NOEXPR         PIC S9(15)V9(2) COMP-3.
      *        10  F007-AMT-LASTEXPRNPAY   PIC S9(15)V9(2) COMP-3.
      *        10  F007-AMT-PRVEXPRNPAY    PIC S9(15)V9(2) COMP-3.
      *        10  F007-IRT                PIC S9(3)V9(6)  COMP-3.
      *        10  F007-FLG-GUAPLCY        PIC X.
      *        10  F007-FLG-RFNC           PIC X.
      *        10  F007-COD-COMMPROD       PIC X(6).
      *        10  F007-PER-RTN            PIC S9(3) COMP-3.
      *        10  F007-FLG-INTF           PIC X.
      *        10  F007-FLG-MOD            PIC X.
      *        10  F007-ENT-LINKACC        PIC X(4).
      *        10  F007-BRN-LINKACC        PIC X(4).
      *        10  F007-ACC-LINK           PIC X(10).
      *        10  F007-TYP-MATFLG         PIC X.
      *        10  F007-COD-COLT           PIC X(3).
      *        10  F007-FLG-LEGJNTRESP     PIC X.
      *        10  F007-ENT-LASTMOD        PIC X(4).
      *        10  F007-BRN-LASTMOD        PIC X(4).
      *        10  F007-COD-LASTMODUSER    PIC X(8).
      *        10  F007-COD-LASTMODTRM     PIC X(8).
      *        10  F007-STP                PIC X(26).
      *        10  F007-TYP-RISKST         PIC X.
      *        10  F007-ENT-LINK           PIC X(4).
      *        10  F007-BRN-LINK           PIC X(4).
      *        10  F007-ACC-LINK-A1        PIC X(10).
      *        10  F007-ENT-NEGT           PIC X(4).
      *        10  F007-BRN-NEGT           PIC X(4).
      *        10  F007-DAT-ST             PIC X(10).
      *        10  F007-MAXQNTY            PIC S9(5) COMP-3.
      *        10  F007-AVA1               PIC X(10).
      *        10  F007-AVA2               PIC X(10).
      *        10  F007-AVA3               PIC X(10).
      *        10  F007-FLG-AVA1           PIC X(1).
      *        10  F007-FLG-AVA2           PIC X(1).
      *        10  F007-FLG-AVA3           PIC X(1).
      *        10  F007-AMT-AVA1           PIC S9(13)V9(2) COMP-3.
      *        10  F007-AMT-AVA2           PIC S9(13)V9(2) COMP-3.
      *        10  F007-AMT-AVA3           PIC S9(13)V9(2) COMP-3.
      *        10  F007-DAT-AVA1           PIC X(10).
      *        10  F007-DAT-AVA2           PIC X(10).
      *        10  F007-DAT-AVA3           PIC X(10).
      *        10  FILLER                  PIC X(11).
      *        10  F007-ENT                PIC X(4).
      *        10  F007-COD-PROD           PIC X(2).
      *        10  F007-ENT-CAC            PIC X(4).
      *        10  F007-CEN-CAC            PIC X(4).
      *        10  F007-NUM-RISK           PIC X(10).
      *        10  F007-RISKSEQ            PIC S9(3) COMP-3.
      *        10  F007-ENT-OWN            PIC X(4).
      *        10  F007-CEN-OWN            PIC X(4).
      *        10  F007-TYP-RISK           PIC X(2).
      *        10  F007-DAT-FML            PIC X(10).
      *        10  F007-DAT-MAT            PIC X(10).
      *        10  F007-AMT-FML            PIC S9(15)V9(2) COMP-3.
      *        10  F007-AMT-AVA            PIC S9(15)V9(2) COMP-3.
      *        10  F007-DEBTBAL            PIC S9(15)V9(2) COMP-3.
      *        10  F007-EXPRBAL            PIC S9(15)V9(2) COMP-3.
      *        10  F007-COD-SLPAY          PIC X(4).
      *        10  F007-FLG-SLPAYRISK      PIC X.
      *        10  F007-DAT-NPAY           PIC X(10).
      *        10  F007-NUM-NPAY           PIC S9(3) COMP-3.
      *        10  F007-AMT-NPAY           PIC S9(15)V9(2) COMP-3.
      *05  F007-CUN                        PIC X(8).
      *05  F007-COD-CRG                    PIC X(3).
      *05  F007-MGT-SECTOR                 PIC X(2).
      *05  F007-COD-OOT                    PIC X(02).
      ******************************************************************

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 118
      * STMT END LINE NUMBER : 122
           PERFORM 100000-START.

           PERFORM 200000-PROCESS.

           PERFORM 300000-END.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 128
      * STMT END LINE NUMBER : 136
       100000-START.

           SET INP-NO-END TO TRUE.

           OPEN INPUT  INPUT-FILE
                OUTPUT OUTPUT-FILE.


           PERFORM RETRIEVE-ENTITY.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 145
      * STMT END LINE NUMBER : 171
       RETRIEVE-ENTITY.
      *
           INITIALIZE VA-QBEC9900-01

           CALL CA-QB8C9900 USING VA-QBEC9900-01

           EVALUATE TRUE

               WHEN QBEC9900-88-COD-RETURN-OK

                   MOVE QBEC9900-DATA-PARAM  TO QBEC999-DATA-PARAM

               WHEN OTHER

                   INITIALIZE QRECDB2

                   MOVE CA-PROGRAM           TO DB2-DES-PGM
                   MOVE CA-QB8C9900          TO DB2-OBJECT
                   MOVE CA-A                 TO DB2-ABEND-DB2
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                   MOVE QBEC9900-COD-RETURN  TO DB2-CODERR
                   MOVE QBEC9900-FILE-STATUS TO DB2-REFERENCE1
                   MOVE SPACES               TO DB2-SQLCA
                                                DB2-STATEMENT

                   PERFORM ABEND-PROGRAM-QR4CDB0

           END-EVALUATE.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 177
      * STMT END LINE NUMBER : 195
       200000-PROCESS.



           INITIALIZE RVFC007.


           PERFORM 210000-READ-RECORD.

           PERFORM
             UNTIL INP-YES-END

              PERFORM 220000-CALC-PERMISS-AND-WRITE


              INITIALIZE RVFC007

              PERFORM 210000-READ-RECORD
           END-PERFORM.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 201
      * STMT END LINE NUMBER : 210
       210000-READ-RECORD.


           READ INPUT-FILE INTO RVFC007

               AT END
                   SET INP-YES-END TO TRUE
               NOT AT END
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                   CONTINUE
           END-READ.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 216
      * STMT END LINE NUMBER : 268
       220000-CALC-PERMISS-AND-WRITE.

              EVALUATE F007-COD-PROD
               WHEN CA-DEPOSIT1
               WHEN CA-DEPOSIT2
               WHEN CA-DEPOSIT3

                   MOVE F007-AMT-FML TO F007-AMT-AVA1

               WHEN CA-LOAN

                   COMPUTE F007-AMT-AVA1 =    F007-DEBTBAL
                                            - F007-AMT-CAP
                                            - F007-AMT-ITR
                                            - F007-AMT-COM

                   IF  F007-AMT-AVA1 < 0

                       MOVE ZEROS TO F007-AMT-AVA1
                   END-IF

               WHEN OTHER

                   MOVE ZEROS          TO F007-AMT-AVA1
           END-EVALUATE.


           IF  F007-TYP-RISKST  NOT EQUAL  '0'
               MOVE  ZEROS  TO F007-AMT-AVA1
           END-IF.



           EVALUATE F007-COD-PROD
              WHEN CA-LOAN
                IF F007-AMT-AVA < F007-AMT-FML
                    COMPUTE F007-PER-RTN =
                    ((F007-AMT-FML - F007-AMT-AVA) -
                     (F007-DEBTBAL - F007-AMT-ITR - F007-AMT-COM)) /
                     (F007-AMT-FML - F007-AMT-AVA) * 100
                ELSE
                    MOVE ZEROS TO F007-PER-RTN
                END-IF

                IF  F007-PER-RTN  <  0
                    MOVE ZEROS  TO  F007-PER-RTN
                END-IF
              WHEN OTHER
                MOVE ZEROS  TO  F007-PER-RTN
           END-EVALUATE


           WRITE RE-OUTPUT FROM RVFC007.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 276
      * STMT END LINE NUMBER : 281
       300000-END.

           CLOSE INPUT-FILE
                 OUTPUT-FILE

      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
           STOP RUN.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:RV3C0100
      * PROGRAM PATH : .../zOS Cobol/RV3C0100.cbl
      * STMT START LINE NUMBER : 286
      * STMT END LINE NUMBER : 288
       ABEND-PROGRAM-QR4CDB0.
      *
           CALL CA-QR4CDB0 USING QRECDB2.
      ******************************************************************
           EXIT PROGRAM.
