      ******************************************************************
      * Created: Mon, 5 Feb 2024 09:31:21 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: PGBPRTXN
      * Workbook id: f9766029-9bd7-4630-9db5-83f9709bf2e8
      * Project: $clientCOBOL_fa79be2a-c77c-4d3f-a56e-fdec6fe02b1f
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. PGBPRTXN.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
      ******************************************************************
           SELECT CUSTINPT ASSIGN TO DDCUSTIN
           ORGANIZATION IS SEQUENTIAL
           FILE STATUS IS WS-CUSTIN-FS.
      ******************************************************************
           SELECT ERRFILE ASSIGN TO DDERRFIL
           ORGANIZATION IS SEQUENTIAL
           FILE STATUS IS WS-ERRFIL-FS.
      ******************************************************************

       DATA DIVISION.
       FILE SECTION.
      ******************************************************************
        FD CUSTINPT.

        COPY CUSTTRAN.
      ******************************************************************
      * PATH : .../Cobol Include/CUSTTRAN.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 CUSTINPT-FILE.
      *    05 CUSTIN-PRI-KEY.
      *       10 CUSTIN-REQ-TYPE                PIC X(02).
      *       10 CUSTIN-CUSTM-NO                PIC X(10).
      *    05 CUSTIN-CUSTM-NAME-FRSTNM          PIC X(15).
      *    05 CUSTIN-CUSTM-NAME-MDLNM           PIC X(8).
      *    05 CUSTIN-CUSTM-NAME-LASTNM          PIC X(15).
      *    05 CUSTIN-CUSTM-ADDR                 PIC X(35).
      *    05 CUSTIN-CUSTM-DOB                  PIC X(10).
      ******************************************************************
        FD ERRFILE.

      ******************************************************************
      * PATH : .../zOS Cobol/PGBPRTXN.cbl
        01 ERROR-REC.
            02 EREC-NO   PIC X(4).
            02 FILLER PIC XX VALUE '-'.
            02 ERROR-MSG  PIC X(74).
      ******************************************************************

       WORKING-STORAGE SECTION.
       01 WS-FILE-STATUS.
          05 WS-CUSTIN-FS          PIC XX.
             88 END-OF-CUSTIN          VALUE '10'.
       01 WS-COUNTERS.
          05 WS-CUSTIN-TOTAL-RECD          PIC 9(03).
      ******************************************************************
       COPY CUSTMSTR.
      * PATH : .../Cobol Include/CUSTMSTR.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01  DCLACN-CUSTM-TABLE.
      *    10 ACN-CUSTM-NAME-MDLNM PIC X(8).
      *    10 ACN-CUSTM-NAME-LASTNM PIC X(15).
      *    10 ACN-CUSTM-ADDR       PIC X(35).
      *    10 ACN-CUSTM-DOB        PIC X(10).
      *    10 ACN-CUSTM-NO          PIC S9(9) USAGE COMP.
      *    10 ACN-CUSTM-NAME-FRSTNM PIC X(15).
      ******************************************************************
        COPY SQLCA.
      * PATH : .../Cobol Include/SQLCA.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      * 01 SQLCA.
      *    05 SQLCODE     PIC S9(9) COMP-5.
      ******************************************************************

      * SQLCA DB2 communications area
           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 130
      * STMT END LINE NUMBER : 132
       A2000-PROCESS-CUST-REQST.
             PERFORM R1000-READ-CUST-FILE.
             PERFORM A2100-TAKE-CUST-REQ UNTIL END-OF-CUSTIN.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 136
      * STMT END LINE NUMBER : 147
       A2100-TAKE-CUST-REQ.

             EVALUATE TRUE
             WHEN CUSTIN-REQ-TYPE = '01'
                  PERFORM A2200-ADD-CUST-PARA
             WHEN CUSTIN-REQ-TYPE = '02'
                  PERFORM A2300-MOD-CUST-PARA
             WHEN CUSTIN-REQ-TYPE = '03'
                  PERFORM A2400-DEL-CUST-PARA
             END-EVALUATE.

             PERFORM R1000-READ-CUST-FILE.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 151
      * STMT END LINE NUMBER : 186
       A2200-ADD-CUST-PARA.

           MOVE CUSTIN-CUSTM-NAME-FRSTNM  TO ACN-CUSTM-NAME-FRSTNM.
           MOVE CUSTIN-CUSTM-NAME-MDLNM   TO ACN-CUSTM-NAME-MDLNM.
           MOVE CUSTIN-CUSTM-NAME-LASTNM  TO ACN-CUSTM-NAME-LASTNM.
           MOVE CUSTIN-CUSTM-ADDR         TO ACN-CUSTM-ADDR.
           MOVE CUSTIN-CUSTM-DOB          TO ACN-CUSTM-DOB.

           EXEC SQL
                INSERT INTO CUSTM_TABLE
                (
                  CUSTM_NAME_FRSTNM        ,
                  CUSTM_NAME_MDLNM         ,
                  CUSTM_NAME_LASTNM        ,
                  CUSTM_ADDR               ,
                  CUSTM_DOB
                )
                VALUES
                (
                  :ACN-CUSTM-NAME-FRSTNM   ,
                  :ACN-CUSTM-NAME-MDLNM    ,
                  :ACN-CUSTM-NAME-LASTNM   ,
                  :ACN-CUSTM-ADDR          ,
                  :ACN-CUSTM-DOB
                )
           END-EXEC.

           EVALUATE TRUE
           WHEN SQLCODE = 0
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                CONTINUE
           WHEN OTHER
                DISPLAY 'CUST TABLE INSERT SQLCODE -',SQLCODE
                MOVE '0001'                            TO EREC-NO
                MOVE '***UNABLE TO INSERT CUSTOMER***' TO ERROR-MSG
                PERFORM W1000-WRITE-ERRFILE-PARA
           END-EVALUATE.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 190
      * STMT END LINE NUMBER : 213
       A2300-MOD-CUST-PARA.
           MOVE CUSTIN-CUSTM-NO           TO ACN-CUSTM-NO.
           MOVE CUSTIN-CUSTM-NAME-FRSTNM  TO ACN-CUSTM-NAME-FRSTNM.
           MOVE CUSTIN-CUSTM-NAME-MDLNM   TO ACN-CUSTM-NAME-MDLNM.
           MOVE CUSTIN-CUSTM-NAME-LASTNM  TO ACN-CUSTM-NAME-LASTNM.
           MOVE CUSTIN-CUSTM-ADDR         TO ACN-CUSTM-ADDR.
           MOVE CUSTIN-CUSTM-DOB          TO ACN-CUSTM-DOB.

           EXEC SQL
                UPDATE CUSTM_TABLE   SET
                  CUSTM_NAME_FRSTNM = :ACN-CUSTM-NAME-FRSTNM,
                  CUSTM_NAME_MDLNM = :ACN-CUSTM-NAME-MDLNM,
                  CUSTM_NAME_LASTNM = :ACN-CUSTM-NAME-LASTNM,
                  CUSTM_ADDR = :ACN-CUSTM-ADDR,
                  CUSTM_DOB  = :ACN-CUSTM-DOB
                WHERE CUSTM_NO = :ACN-CUSTM-NO
              END-EXEC.

           EVALUATE TRUE
            WHEN SQLCODE = 0
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                 CONTINUE
            WHEN OTHER
                 DISPLAY 'CUST TABLE UPDATE SQLCODE -',SQLCODE
           END-EVALUATE.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 217
      * STMT END LINE NUMBER : 230
       A2400-DEL-CUST-PARA.
             MOVE CUSTIN-CUSTM-NO           TO ACN-CUSTM-NO.

             EXEC SQL
                DELETE FROM CUSTM_TABLE
                WHERE CUSTM_NO = :ACN-CUSTM-NO
             END-EXEC.

             EVALUATE TRUE
             WHEN SQLCODE = 0
      * TODO : CHECK THE FOLLOWING <CONTINUE/NEXT SENTENCE/GO TO/GO
      * BACK/RETURN/STOP RUN/EXIT/EXIT PROGRAM> STATEMENT
                  CONTINUE
             WHEN OTHER
                  DISPLAY 'CUST TABLE DELETE SQLCODE -',SQLCODE
             END-EVALUATE.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 476
      * STMT END LINE NUMBER : 491
       R1000-READ-CUST-FILE.
             READ CUSTINPT
             END-READ.

             EVALUATE TRUE
             WHEN WS-CUSTIN-FS = '00'
              COMPUTE WS-CUSTIN-TOTAL-RECD = WS-CUSTIN-TOTAL-RECD + 1
             WHEN WS-CUSTIN-FS = '10'
              SET END-OF-CUSTIN TO TRUE
             WHEN OTHER
              SET END-OF-CUSTIN TO TRUE
              DISPLAY 'CUST TRAN FILE ERROR -',WS-CUSTIN-FS
              MOVE 'R001'                            TO EREC-NO
              MOVE '***CUST FILE READ ERROR***'      TO ERROR-MSG
              PERFORM W1000-WRITE-ERRFILE-PARA
             END-EVALUATE.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:PGBPRTXN
      * PROGRAM PATH : .../zOS Cobol/PGBPRTXN.cbl
      * STMT START LINE NUMBER : 513
      * STMT END LINE NUMBER : 514
       W1000-WRITE-ERRFILE-PARA.
             WRITE ERROR-REC.
      ******************************************************************
           EXIT PROGRAM.
